[package]
name = "lplib"
edition = "2021"

[dependencies]
# put any compatible core deps here
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "1.0.3"

[lib]
crate-type = ["rlib"]

[features]
default = ["std"]
std = []

[package.metadata.docs.rs]
features = ["std"]