[package]
name = "lp-alloc"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["thread_local"]

[dependencies]
spin = { version = "0.9", features = ["portable_atomic"] }
thread_local = { version = "1.1", optional = true }

[dev-dependencies]

