[package]
name = "lp-alloc"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["thread_local"]

[dependencies]
thread_local = { version = "1.1", optional = true }
critical-section = "1.2"

[dev-dependencies]

