[package]
name = "lp-schema-gen"
edition = "2021"

[dependencies]
lp-data = { path = "../../crates/lp-data", features = ["alloc", "derive"] }
lp-data-derive = { path = "../../crates/lp-data-derive" }
lp-math = { path = "../../crates/lp-math" }
serde = { version = "1", features = ["derive"] }