[package]
name = "lp-pool"
version = "0.1.0"
edition = "2021"

[features]
default = ["alloc-meta", "std"]
alloc-meta = []  # Enable allocation metadata tracking with type and scope information
std = []

[dependencies]
allocator-api2 = "0.2"
spin = { version = "0.9", features = ["portable_atomic"] }

[dev-dependencies]

