[package]
name = "lplib"
edition = "2021"

[dependencies]
# put any compatible core deps here

[lib]
crate-type = ["rlib"]

[features]
default = ["std"]
std = []

[package.metadata.docs.rs]
features = ["std"]