[package]
name = "lp-math"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
schemars = { version = "1.0", optional = true }
